import Foundation

// Vocabulary list from mywords.js
struct VocabularyData {
    static let words: [String] = [
        // A
        "abandon", "abide by", "abnormal", "abolish", "abrupt", "absence",
        "absolute", "absorb", "abstract", "absurd", "abundant", "abuse",
        "academic", "accelerate", "accent", "acceptance", "access", "accident",
        "accommodate", "accomplish", "accordance", "accordingly", "account for",
        "accumulate", "accurate", "accuse", "accustomed", "achievement",
        "acknowledge", "acquaintance", "acquire", "acquisition", "adapt",
        "adequate", "adjust", "administer", "admire", "admission", "admit",
        "adolescent", "adopt", "adore", "advance", "advantage", "adventure",
        "adverse", "advertise", "advocate", "affect", "afford", "afraid",
        "aftermath", "aggravate", "aggregate", "aggressive", "agreeable",
        "agreement", "agriculture", "aid", "aircraft", "alert", "allocate",
        "allowance", "ally", "along with", "alter", "alternative", "although",
        "altitude", "altogether", "amateur", "amaze", "ambassador", "ambiguous",
        "ambition", "ample", "amuse", "analogy", "analysis", "analyze",
        "ancestor", "anchor", "ancient", "anger", "angle", "anniversary",
        "announce", "annoy", "annual", "anticipate", "anxiety", "apologize",
        "apparent", "appeal", "appear", "appetite", "applaud", "appoint",
        "appreciate", "approach", "appropriate", "approve", "approximate",
        "arbitrary", "architect", "argue", "arise", "arithmetic", "arrange",
        "arrest", "arrogant", "article", "artificial", "ashamed", "aspect",
        "aspiration", "assemble", "assert", "assess", "asset", "assign",
        "assist", "associate", "assume", "assure", "astonish", "attach",
        "attack", "attain", "attempt", "attend", "attention", "attitude",
        "attract", "attribute", "auction", "audience", "authentic", "authority",
        "automatic", "available", "aware", "awkward",
        // B
        "background", "backward", "bacteria", "balance", "ban", "bankrupt",
        "barely", "bargain", "barrier", "basis", "bear", "beat", "become",
        "beforehand", "behave", "behavior", "belong", "beneficial", "benefit",
        "betray", "bias", "bill", "bind", "birth", "bitter", "blame",
        "blank", "blend", "bless", "block", "bloom", "board", "boast",
        "bold", "bomb", "border", "bore", "bother", "bound", "boundary",
        "brave", "breach", "break", "breakthrough", "breed", "bribe",
        "brief", "bright", "brilliant", "broadcast", "broaden", "budget",
        "bulk", "burden", "burn", "burst", "bury", "bush", "business",
        // C
        "calculate", "call for", "calm", "campaign", "cancel", "candidate",
        "capable", "capacity", "capture", "career", "careful", "cargo",
        "carry out", "case", "cast", "casual", "catch", "category", "cater",
        "cause", "caution", "cease", "celebrate", "celebrity", "cell",
        "census", "center", "central", "century", "ceremony", "certain",
        "certificate", "chain", "challenge", "champion", "chance", "change",
        "channel", "chaos", "chapter", "character", "characteristic", "charge",
        "charity", "charm", "chart", "chase", "chat", "cheap", "check",
        "cheerful", "chemical", "chief", "childhood", "choice", "choose",
        "chronic", "chunk", "circuit", "circulate", "circumstance", "cite",
        "citizen", "civil", "claim", "clarify", "clash", "class", "classic",
        "classify", "clause", "clerk", "clever", "client", "climate", "climb",
        "cling", "clinic", "clock", "close", "clue", "clumsy", "cluster",
        "coach", "coal", "coarse", "coast", "code", "coincide", "collapse",
        "colleague", "collect", "college", "collide", "colony", "color",
        "column", "combat", "combine", "come", "comfort", "command",
        "commence", "comment", "commerce", "commercial", "commission",
        "commit", "committee", "commodity", "common", "communicate",
        "community", "commute", "compact", "companion", "company", "compare",
        "compatible", "compel", "compensate", "compete", "competent",
        "compile", "complain", "complement", "complete", "complex",
        "complicate", "component", "compose", "compound", "comprehend",
        "comprehensive", "comprise", "compromise", "compulsory", "conceal",
        "concede", "conceive", "concentrate", "concept", "concern", "concise",
        "conclude", "concrete", "condemn", "condition", "conduct", "confer",
        "confess", "confident", "confine", "confirm", "conflict", "conform",
        "confront", "confuse", "congratulate", "congress", "connect",
        "conscience", "conscious", "consensus", "consent", "consequence",
        "consequently", "conservative", "consider", "considerable", "consist",
        "consistent", "constant", "constitute", "constrain", "construct",
        "consult", "consume", "consumer", "contact", "contain", "contaminate",
        "contemporary", "contempt", "contend", "content", "contest", "context",
        "continent", "continue", "continuous", "contract", "contradict",
        "contrary", "contrast", "contribute", "control", "controversial",
        "convenient", "convention", "conventional", "convert", "convey",
        "convict", "convince", "cooperate", "coordinate", "cope", "core",
        "corporate", "correct", "correspond", "cost", "cotton", "council",
        "counsel", "count", "counter", "country", "countryside", "county",
        "couple", "courage", "course", "court", "cousin", "cover", "crack",
        "craft", "crash", "crawl", "create", "creature", "credential",
        "credit", "creep", "crew", "crime", "criminal", "crisis", "criterion",
        "critic", "critical", "criticism", "criticize", "crop", "cross",
        "crowd", "crucial", "cruel", "crush", "cry", "cultivate", "culture",
        "cure", "curious", "currency", "current", "curriculum", "curse",
        "curve", "custom", "customer", "cut", "cycle", // D
        "daily", "damage", "dare", "dark", "data", "date", "dawn", "deal",
        "debate", "debt", "decade", "decay", "deceit", "deceive", "decide",
        "decimal", "decision", "decisive", "deck", "declare", "decline",
        "decorate", "decrease", "dedicate", "deduce", "deed", "deem",
        "defeat", "defect", "defend", "defense", "deficiency", "deficit",
        "define", "definite", "definition", "defy", "degree", "delay",
        "delegate", "deliberate", "delicate", "delicious", "delight",
        "deliver", "demand", "democracy", "democratic", "demonstrate",
        "denote", "deny", "depart", "department", "depend", "dependent",
        "depict", "deposit", "depress", "deprive", "derive", "descend",
        "describe", "description", "desert", "deserve", "design", "designate",
        "desirable", "desire", "despair", "desperate", "despite", "destination",
        "destiny", "destroy", "destruction", "detach", "detail", "detect",
        "deteriorate", "determine", "develop", "deviate", "device", "devise",
        "devote", "diagnose", "dictate", "die", "differ", "difference",
        "differentiate", "difficult", "diffuse", "dig", "digest", "digital",
        "dignity", "dilemma", "diligent", "dim", "dimension", "diminish",
        "dine", "dip", "diploma", "diplomatic", "direct", "direction",
        "directory", "disable", "disadvantage", "disagree", "disappear",
        "disappoint", "disaster", "discard", "discharge", "discipline",
        "disclose", "discount", "discourage", "discourse", "discover",
        "discreet", "discrepancy", "discriminate", "discuss", "disease",
        "disgrace", "disguise", "disgust", "dish", "dismiss", "disorder",
        "disperse", "display", "dispose", "dispute", "disrupt", "dissolve",
        "distance", "distant", "distinct", "distinguish", "distort",
        "distract", "distribute", "district", "disturb", "diverse", "divert",
        "divide", "divine", "division", "divorce", "do", "doctor",
        "document", "domain", "domestic", "dominant", "dominate", "donate",
        "doom", "dose", "dot", "doubt", "draft", "drag", "drain", "drama",
        "dramatic", "draw", "drawback", "drawer", "dread", "dream", "dress",
        "drift", "drill", "drink", "drive", "drop", "drown", "drug",
        "dry", "dual", "dubious", "due", "dull", "dumb", "dump", "duration",
        "during", "dusk", "dust", "duty", "dwell", "dynamic", // E
        "eager", "earn", "earth", "ease", "echo", "economic", "economy",
        "edge", "edit", "educate", "education", "effect", "effective",
        "efficiency", "efficient", "effort", "either", "elaborate", "elect",
        "election", "electric", "elegant", "element", "elementary", "eliminate",
        "elite", "else", "embarrass", "embassy", "embed", "embody", "embrace",
        "emerge", "emergency", "emit", "emotion", "emotional", "emphasis",
        "emphasize", "empire", "empirical", "employ", "employee", "employer",
        "employment", "empty", "enable", "enact", "enclose", "encounter",
        "encourage", "end", "endeavor", "endless", "endorse", "endure",
        "enemy", "energy", "enforce", "engage", "engine", "engineer",
        "enhance", "enjoy", "enormous", "ensure", "enter", "enterprise",
        "entertain", "enthusiasm", "entire", "entitle", "entity", "entrance",
        "entrepreneur", "entry", "envelope", "environment", "envisage",
        "episode", "equal", "equation", "equip", "equipment", "equivalent",
        "era", "eradicate", "erase", "erect", "erode", "error", "erupt",
        "escape", "escort", "especially", "essay", "essence", "essential",
        "establish", "estate", "estimate", "eternal", "ethic", "evacuate",
        "evaluate", "evaporate", "even", "evening", "event", "eventually",
        "ever", "evidence", "evil", "evoke", "evolution", "evolve", "exact",
        "exaggerate", "exam", "examine", "example", "exceed", "excellent",
        "except", "exception", "excess", "exchange", "excite", "exclude",
        "excuse", "execute", "executive", "exempt", "exercise", "exert",
        "exhaust", "exhibit", "exile", "exist", "exit", "expand", "expansion",
        "expect", "expedition", "expel", "expend", "expense", "expensive",
        "experience", "experiment", "expert", "expertise", "expire",
        "explicit", "explode", "exploit", "explore", "explosion", "export",
        "expose", "exposure", "express", "extend", "extension", "extensive",
        "extent", "external", "extinct", "extra", "extract", "extraordinary",
        "extravagant", "extreme", "eye",
        // F
        "fabric", "face", "facilitate", "facility", "fact", "factor",
        "factory", "faculty", "fade", "fail", "failure", "fair", "faith",
        "fake", "fall", "false", "fame", "familiar", "family", "famous",
        "fan", "fancy", "far", "fare", "farm", "fascinate", "fashion",
        "fast", "fasten", "fat", "fatal", "fate", "father", "fatigue",
        "fault", "favor", "favorite", "fear", "feasible", "feast", "feat",
        "feature", "federal", "fee", "feed", "feel", "fellow", "female",
        "fertile", "fever", "few", "fiber", "fiction", "field", "fierce",
        "fight", "figure", "file", "fill", "filter", "final", "finance",
        "financial", "find", "fine", "finger", "finish", "finite", "fire",
        "firm", "first", "fiscal", "fit", "fix", "flag", "flame", "flash",
        "flat", "flatter", "flavor", "flaw", "flee", "fleet", "flesh",
        "flexible", "flight", "fling", "float", "flock", "flood", "floor",
        "flour", "flourish", "flow", "fluctuate", "fluent", "fluid",
        "focus", "fog", "fold", "folk", "follow", "following", "fond",
        "food", "fool", "foot", "forbid", "force", "forecast", "forehead",
        "foreign", "foremost", "foresee", "forest", "forever", "forge",
        "forget", "forgive", "form", "formal", "format", "formation",
        "former", "formidable", "formula", "forth", "fortunate", "fortune",
        "forum", "forward", "foster", "foul", "found", "foundation", "fountain",
        "fraction", "fragile", "fragment", "frame", "framework", "frank",
        "free", "freeze", "freight", "frequency", "frequent", "fresh",
        "friction", "friend", "fright", "frighten", "front", "frontier",
        "frost", "frown", "fruit", "frustrate", "fuel", "fulfill", "full",
        "fun", "function", "fund", "fundamental", "funeral", "fur", "furious",
        "furnish", "furniture", "further", "furthermore", "fuse", "fuss",
        "future",
        // G
        "gain", "gamble", "gap", "garage", "garden", "garment", "gas",
        "gasp", "gate", "gather", "gauge", "gaze", "gear", "gender",
        "gene", "general", "generate", "generation", "generous", "genius",
        "gentle", "genuine", "gesture", "get", "ghost", "giant", "gift",
        "girl", "give", "glad", "glance", "glare", "glass", "glide",
        "glimpse", "global", "globe", "glory", "glove", "glow", "glue",
        "goal", "goat", "gold", "golden", "good", "govern", "government",
        "governor", "grace", "grade", "gradual", "graduate", "grain",
        "grand", "grant", "grape", "graph", "grasp", "grass", "grateful",
        "gratify", "grave", "gravity", "gray", "great", "greedy", "green",
        "greet", "grief", "grim", "grind", "grip", "groan", "grocery",
        "gross", "ground", "group", "grow", "growth", "guarantee", "guard",
        "guess", "guest", "guide", "guideline", "guilt", "guilty", "gulf",
        "gun", "gut",
        // H
        "habit", "habitat", "hail", "half", "hall", "halt", "hand", "handful",
        "handle", "handy", "hang", "happen", "happy", "harbor", "hard",
        "harden", "hardly", "hardship", "harm", "harmful", "harmony",
        "harness", "harsh", "harvest", "haste", "hasty", "hat", "hatch",
        "hate", "hatred", "haul", "hazard", "head", "headache", "headline",
        "heal", "health", "heap", "hear", "heart", "heat", "heaven", "heavy",
        "hedge", "heel", "height", "heir", "helicopter", "hell", "help",
        "hence", "herb", "herd", "heritage", "hero", "hesitate", "hide",
        "high", "highway", "hill", "hint", "hire", "historic", "historical",
        "history", "hit", "hobby", "hold", "hole", "holiday", "hollow",
        "holy", "home", "homework", "honest", "honey", "honor", "hook",
        "hope", "horizon", "horn", "horror", "horse", "hospital", "host",
        "hostage", "hostile", "hot", "hotel", "hour", "house", "household",
        "hover", "however", "huge", "human", "humble", "humid", "humiliate",
        "humor", "hunger", "hunt", "hurry", "hurt", "husband", "hut",
        "hydrogen", "hypothesis",
        // I
        "ice", "idea", "ideal", "identical", "identify", "identity", "idle",
        "ignite", "ignorance", "ignorant", "ignore", "ill", "illegal",
        "illness", "illuminate", "illusion", "illustrate", "image", "imagine",
        "imitate", "immediate", "immense", "immerse", "immigrant", "imminent",
        "immune", "impact", "impair", "impart", "impatient", "imperative",
        "implement", "implicate", "imply", "import", "important", "impose",
        "impossible", "impress", "impression", "impressive", "improve",
        "improvement", "impulse", "incentive", "incident", "incline",
        "include", "income", "incorporate", "increase", "incredible", "incur",
        "indeed", "independent", "index", "indicate", "indifferent",
        "indigenous", "indispensable", "individual", "induce", "indulge",
        "industry", "inevitable", "infant", "infect", "infer", "inference",
        "inferior", "infinite", "inflation", "inflict", "influence", "inform",
        "informal", "information", "infrastructure", "ingenious", "ingredient",
        "inhabit", "inherent", "inherit", "inhibit", "initial", "initiate",
        "initiative", "inject", "injure", "inn", "innocent", "innovate",
        "innovation", "input", "inquire", "inquiry", "insect", "insert",
        "inside", "insight", "insist", "inspect", "inspire", "install",
        "instance", "instant", "instead", "instinct", "institute", "institution",
        "instruct", "instruction", "instrument", "insult", "insure",
        "integrate", "integrity", "intellect", "intelligent", "intend",
        "intense", "intensify", "intent", "intention", "interact",
        "interest", "interfere", "interim", "interior", "intermediate",
        "internal", "international", "interpret", "interrupt", "interval",
        "intervene", "interview", "intimate", "into", "intricate", "intrigue",
        "introduce", "introduction", "invade", "invalid", "invaluable",
        "invariably", "invasion", "invent", "invention", "invest",
        "investigate", "investment", "invisible", "invite", "involve",
        "iron", "irony", "irritate", "island", "isolate", "issue", "item",
        // J
        "jail", "jar", "jaw", "jealous", "jet", "jewel", "job", "jog",
        "join", "joint", "joke", "journal", "journey", "joy", "judge",
        "judicial", "juice", "jump", "junction", "jungle", "junior",
        "jury", "just", "justice", "justify", "juvenile",
        // K
        "keen", "keep", "kettle", "key", "kick", "kid", "kill", "kind",
        "king", "kingdom", "kiss", "kit", "kitchen", "knee", "kneel",
        "knife", "knit", "knock", "knot", "know", "knowledge",
        // L
        "lab", "label", "labor", "laboratory", "lack", "ladder", "lady",
        "lag", "lake", "lamb", "lame", "lamp", "land", "landlord", "landscape",
        "lane", "language", "large", "largely", "last", "late", "lately",
        "later", "latest", "latitude", "latter", "laugh", "launch", "laundry",
        "law", "lawn", "lawyer", "lay", "layer", "lazy", "lead", "leader",
        "leadership", "leading", "leaf", "league", "leak", "lean", "leap",
        "learn", "lease", "least", "leave", "lecture", "left", "leg",
        "legal", "legend", "legislation", "legitimate", "leisure", "lend",
        "length", "lens", "less", "lesson", "let", "letter", "level",
        "liberal", "liberate", "liberty", "library", "license", "lick",
        "lid", "lie", "life", "lift", "light", "like", "likely", "likewise",
        "limit", "limitation", "line", "linear", "linger", "link", "lion",
        "lip", "liquid", "list", "listen", "literacy", "literally", "literary",
        "literature", "little", "live", "lively", "liver", "living", "load",
        "loan", "local", "locate", "location", "lock", "log", "logic",
        "logical", "lonely", "long", "look", "loose", "lose", "loss", "lot",
        "loud", "love", "low", "lower", "loyal", "loyalty", "luck", "lucky",
        "lump", "lunch", "lung", "luxury",
        // M
        "machine", "mad", "magazine", "magic", "magnet", "magnetic",
        "magnificent", "magnitude", "mail", "main", "mainland", "maintain",
        "maintenance", "major", "majority", "make", "male", "mall", "man",
        "manage", "management", "manager", "manifest", "manipulate", "manner",
        "manual", "manufacture", "manufacturer", "many", "map", "march",
        "margin", "marine", "mark", "market", "marriage", "married", "marry",
        "marsh", "marvelous", "mask", "mass", "massacre", "massive", "master",
        "match", "mate", "material", "matter", "mature", "maximum", "may",
        "maybe", "mayor", "meal", "mean", "meaning", "means", "meantime",
        "meanwhile", "measure", "meat", "mechanic", "mechanical", "mechanism",
        "medal", "medical", "medicine", "medieval", "meditate", "medium",
        "meet", "meeting", "melody", "melt", "member", "memorial", "memory",
        "menace", "mend", "mental", "mention", "menu", "merchant", "mere",
        "merely", "merge", "merit", "merry", "mess", "message", "metal",
        "method", "metropolitan", "middle", "midnight", "might", "mild",
        "mile", "military", "milk", "mill", "million", "mind", "mine",
        "mineral", "minimal", "minimize", "minimum", "minister", "ministry",
        "minor", "minority", "minute", "miracle", "mirror", "misery",
        "mislead", "miss", "missile", "missing", "mission", "mistake",
        "mix", "mixture", "moan", "mobile", "mock", "mode", "model",
        "moderate", "modern", "modest", "modify", "moist", "moisture",
        "molecule", "moment", "momentum", "money", "monitor", "monkey",
        "monopoly", "monster", "month", "monument", "mood", "moon", "moral",
        "more", "moreover", "morning", "mortal", "mortgage", "most", "mostly",
        "motel", "mother", "motion", "motive", "motor", "mount", "mountain",
        "mourn", "mouse", "mouth", "move", "movement", "movie", "much",
        "mud", "multiple", "multiply", "murder", "muscle", "museum",
        "mushroom", "music", "must", "mutual",
        // N
        "nail", "naive", "naked", "name", "namely", "narrow", "nasty",
        "nation", "national", "native", "natural", "naturally", "nature",
        "naughty", "naval", "navigation", "navy", "near", "nearby", "nearly",
        "neat", "necessarily", "necessary", "necessity", "neck", "need",
        "needle", "negative", "neglect", "negotiate", "neighbor", "neither",
        "nephew", "nerve", "nervous", "nest", "net", "network", "neutral",
        "never", "nevertheless", "new", "news", "next", "nice", "niece",
        "night", "nightmare", "nine", "no", "noble", "nobody", "nod",
        "noise", "noisy", "nominate", "none", "nonetheless", "nonsense",
        "noon", "nor", "normal", "normally", "north", "nose", "not",
        "notable", "note", "notebook", "nothing", "notice", "notify",
        "notion", "notorious", "novel", "now", "nowadays", "nowhere",
        "nuclear", "number", "numerous", "nurse", "nurture", "nut",
        "nutrition",
        // O
        "obey", "object", "objection", "objective", "obligation", "oblige",
        "observe", "observer", "obsess", "obstacle", "obtain", "obvious",
        "occasion", "occasional", "occupation", "occupy", "occur", "ocean",
        "odd", "odds", "off", "offend", "offer", "office", "officer",
        "official", "offspring", "often", "oil", "old", "omit", "on",
        "once", "one", "ongoing", "onion", "only", "open", "operate",
        "operation", "operator", "opinion", "opponent", "opportunity",
        "oppose", "opposite", "oppress", "opt", "optical", "optimistic",
        "option", "or", "oral", "orbit", "orchestra", "order", "ordinary",
        "organ", "organic", "organism", "organization", "organize", "orient",
        "origin", "original", "originate", "other", "otherwise", "ought",
        "ounce", "out", "outcome", "outdoor", "outer", "outlet", "outline",
        "output", "outrage", "outset", "outside", "outstanding", "outward",
        "oven", "over", "overall", "overcome", "overhead", "overlook",
        "overnight", "overseas", "oversee", "overwhelm", "owe", "own",
        "owner", "ownership", "oxygen",
        // P
        "pace", "pack", "package", "pad", "page", "pain", "painful",
        "paint", "painter", "pair", "palace", "pale", "palm", "pan",
        "panel", "panic", "pants", "paper", "parade", "paragraph", "parallel",
        "parameter", "parcel", "pardon", "parent", "park", "parliament",
        "part", "participate", "particular", "partly", "partner", "party",
        "pass", "passage", "passenger", "passion", "passive", "passport",
        "past", "paste", "pat", "patch", "patent", "path", "patience",
        "patient", "patrol", "pattern", "pause", "pave", "pay", "peace",
        "peaceful", "peak", "pear", "peasant", "peculiar", "peer", "pen",
        "penalty", "pencil", "people", "pepper", "per", "perceive", "percent",
        "percentage", "perception", "perfect", "perform", "performance",
        "perhaps", "period", "permanent", "permission", "permit", "persist",
        "person", "personal", "personality", "personnel", "perspective",
        "persuade", "pessimistic", "pet", "petition", "phase", "phenomenon",
        "philosophy", "phone", "photo", "phrase", "physical", "physician",
        "physics", "pick", "picture", "piece", "pierce", "pig", "pile",
        "pill", "pilot", "pin", "pine", "pink", "pioneer", "pipe", "pit",
        "pitch", "pity", "place", "plain", "plan", "plane", "planet",
        "plant", "plastic", "plate", "platform", "play", "pleasant", "please",
        "pleasure", "plenty", "plot", "plug", "plunge", "plus", "pocket",
        "poem", "poet", "poetry", "point", "poison", "poisonous", "poke",
        "polar", "pole", "police", "policy", "polish", "polite", "political",
        "politician", "politics", "poll", "pollute", "pollution", "pond",
        "pool", "poor", "pop", "popular", "population", "port", "portable",
        "portion", "portrait", "portray", "pose", "position", "positive",
        "possess", "possession", "possible", "possibly", "post", "postpone",
        "pot", "potato", "potential", "pound", "pour", "poverty", "powder",
        "power", "powerful", "practical", "practice", "practitioner", "praise",
        "pray", "preach", "precaution", "precede", "precedent", "precious",
        "precise", "precision", "predecessor", "predict", "predominant",
        "prefer", "preference", "pregnant", "prejudice", "preliminary",
        "premier", "premise", "premium", "preparation", "prepare", "prescribe",
        "presence", "present", "preserve", "preside", "president", "press",
        "pressure", "prestige", "presumably", "presume", "pretend", "pretty",
        "prevail", "prevent", "previous", "prey", "price", "pride", "priest",
        "primarily", "primary", "prime", "primitive", "prince", "princess",
        "principal", "principle", "print", "prior", "priority", "prison",
        "prisoner", "private", "privilege", "prize", "probably", "problem",
        "procedure", "proceed", "process", "proclaim", "produce", "product",
        "production", "productive", "profession", "professional", "professor",
        "proficiency", "profile", "profit", "profound", "progress",
        "prohibit", "project", "prolong", "prominent", "promise", "promote",
        "prompt", "pronounce", "proof", "propaganda", "proper", "property",
        "prophet", "proportion", "proposal", "propose", "prosecute", "prospect",
        "prosper", "protect", "protection", "protective", "protein", "protest",
        "proud", "prove", "provide", "province", "provoke", "psychology",
        "public", "publication", "publicity", "publish", "pull", "pulse",
        "pump", "punch", "punish", "pupil", "purchase", "pure", "purple",
        "purpose", "pursue", "pursuit", "push", "put",
        // Q
        "qualification", "qualify", "quality", "quantity", "quarrel", "quarter",
        "queen", "quest", "question", "questionnaire", "queue", "quick",
        "quiet", "quit", "quite", "quiz", "quote",
        // R
        "rabbit", "race", "racial", "rack", "radar", "radiate", "radiation",
        "radical", "radio", "rage", "raid", "rail", "railroad", "rain",
        "raise", "rally", "range", "rank", "rapid", "rare", "rarely", "rat",
        "rate", "rather", "ratio", "rational", "raw", "ray", "reach",
        "react", "reaction", "read", "ready", "real", "realistic", "reality",
        "realize", "really", "realm", "rear", "reason", "reasonable", "rebel",
        "recall", "receipt", "receive", "recent", "recently", "reception",
        "recession", "recipe", "recipient", "reckon", "recognition", "recognize",
        "recommend", "reconcile", "record", "recover", "recovery", "recruit",
        "recycle", "red", "reduce", "reduction", "redundant", "refer",
        "reference", "refine", "reflect", "reflection", "reform", "refrain",
        "refresh", "refrigerator", "refuge", "refugee", "refund", "refusal",
        "refuse", "regain", "regard", "regarding", "regardless", "regime",
        "region", "register", "regret", "regular", "regulate", "regulation",
        "reinforce", "reject", "relate", "relation", "relationship", "relative",
        "relatively", "relax", "release", "relevant", "relief", "relieve",
        "religion", "religious", "reluctant", "rely", "remain", "remainder",
        "remark", "remarkable", "remedy", "remember", "remind", "remote",
        "remove", "render", "renew", "rent", "repair", "repeat", "repeatedly",
        "repel", "replace", "reply", "report", "represent", "representative",
        "reproduce", "republic", "reputation", "request", "require",
        "requirement", "rescue", "research", "resemble", "reservation",
        "reserve", "reside", "residence", "resident", "resign", "resist",
        "resistance", "resolution", "resolve", "resort", "resource", "respect",
        "respective", "respond", "response", "responsibility", "responsible",
        "rest", "restaurant", "restore", "restrain", "restrict", "restriction",
        "result", "resume", "retail", "retain", "retire", "retreat",
        "retrieve", "return", "reveal", "revenge", "revenue", "reverse",
        "review", "revise", "revival", "revive", "revolution", "reward",
        "rhetoric", "rhythm", "rib", "ribbon", "rich", "rid", "ride",
        "ridiculous", "right", "rigid", "ring", "riot", "rise", "risk",
        "ritual", "rival", "river", "road", "roar", "roast", "rob", "rock",
        "rocket", "role", "roll", "romantic", "roof", "room", "root", "rope",
        "rot", "rotate", "rough", "round", "rouse", "route", "routine",
        "row", "royal", "rub", "rubber", "rude", "ruin", "rule", "rumor",
        "run", "rural", "rush", "rust",
        // S
        "sack", "sacred", "sacrifice", "sad", "safe", "safety", "sail",
        "sailor", "sake", "salad", "salary", "sale", "sales", "salon",
        "salt", "same", "sample", "sanction", "sand", "sandal", "satellite",
        "satisfaction", "satisfy", "saturate", "sauce", "save", "saving",
        "say", "scale", "scan", "scandal", "scarce", "scarcely", "scare",
        "scatter", "scene", "scenery", "scent", "schedule", "scheme",
        "scholar", "scholarship", "school", "science", "scientific", "scientist",
        "scissors", "scold", "scope", "score", "scorn", "scout", "scramble",
        "scrap", "scrape", "scratch", "scream", "screen", "screw", "script",
        "scrutiny", "sculpture", "sea", "seal", "search", "season", "seat",
        "second", "secondary", "secret", "secretary", "section", "sector",
        "secure", "security", "see", "seed", "seek", "seem", "seemingly",
        "segment", "seize", "seldom", "select", "selection", "self", "selfish",
        "sell", "send", "senior", "sensation", "sense", "sensible", "sensitive",
        "sentence", "sentiment", "separate", "sequence", "series", "serious",
        "sermon", "serve", "service", "session", "set", "settle", "settlement",
        "several", "severe", "sew", "sex", "sexual", "shade", "shadow",
        "shake", "shall", "shallow", "shame", "shape", "share", "sharp",
        "shatter", "shave", "she", "shed", "sheep", "sheer", "sheet",
        "shelf", "shell", "shelter", "shield", "shift", "shine", "ship",
        "shirt", "shiver", "shock", "shoe", "shoot", "shop", "shore",
        "short", "shortage", "shortly", "shot", "should", "shoulder", "shout",
        "show", "shower", "shrink", "shrug", "shut", "shy", "sick", "side",
        "sidewalk", "sigh", "sight", "sign", "signal", "signature",
        "significance", "significant", "signify", "silence", "silent", "silk",
        "silly", "silver", "similar", "simple", "simply", "simulate",
        "simultaneous", "sin", "since", "sincere", "sing", "single", "singular",
        "sink", "sir", "sister", "sit", "site", "situate", "situation",
        "size", "sketch", "skill", "skilled", "skim", "skin", "skip",
        "skirt", "skull", "sky", "slab", "slam", "slap", "slash", "slave",
        "sleep", "slice", "slide", "slight", "slightly", "slim", "slip",
        "slogan", "slope", "slow", "slump", "small", "smart", "smash",
        "smell", "smile", "smoke", "smooth", "snake", "snap", "snow",
        "so", "soak", "soap", "soar", "so-called", "soccer", "social",
        "society", "sociology", "sock", "soft", "software", "soil", "solar",
        "soldier", "sole", "solely", "solemn", "solid", "solitary", "solution",
        "solve", "some", "somebody", "somehow", "someone", "something",
        "sometimes", "somewhat", "somewhere", "son", "song", "soon", "sore",
        "sorrow", "sort", "soul", "sound", "soup", "source", "south",
        "sovereign", "space", "spacious", "span", "spare", "spark", "speak",
        "special", "specialist", "specialize", "species", "specific",
        "specify", "specimen", "spectacle", "spectator", "spectrum",
        "speculate", "speech", "speed", "spell", "spend", "sphere", "spill",
        "spin", "spirit", "spiritual", "spit", "spite", "splash", "split",
        "spoil", "spokesman", "sponge", "sponsor", "spontaneous", "spoon",
        "sport", "spot", "spouse", "spray", "spread", "spring", "sprinkle",
        "spy", "squad", "square", "squeeze", "stable", "stack", "stadium",
        "staff", "stage", "stagger", "stain", "stair", "stake", "stale",
        "stall", "stamp", "stand", "standard", "standing", "star", "stare",
        "start", "starve", "state", "statement", "station", "statistic",
        "statue", "status", "stay", "steady", "steal", "steam", "steel",
        "steep", "steer", "stem", "step", "stereotype", "stick", "sticky",
        "stiff", "still", "stimulate", "sting", "stir", "stock", "stomach",
        "stone", "stop", "store", "storm", "story", "stove", "straight",
        "strain", "strange", "stranger", "strap", "strategy", "straw",
        "stray", "stream", "street", "strength", "strengthen", "stress",
        "stretch", "strict", "strike", "striking", "string", "strip",
        "stripe", "strive", "stroke", "stroll", "strong", "structure",
        "struggle", "student", "studio", "study", "stuff", "stumble",
        "stun", "stupid", "subject", "subjective", "submit", "subordinate",
        "subscribe", "subsequent", "subsequently", "subsidy", "substance",
        "substantial", "substitute", "subtle", "subtract", "suburb",
        "subway", "succeed", "success", "successful", "succession", "successor",
        "such", "sudden", "sue", "suffer", "sufficient", "sugar", "suggest",
        "suggestion", "suicide", "suit", "suitable", "suite", "sulfur",
        "sum", "summarize", "summary", "summit", "summon", "sun", "super",
        "superb", "superficial", "superior", "supermarket", "supervise",
        "supper", "supplement", "supply", "support", "suppose", "suppress",
        "supreme", "sure", "surface", "surge", "surgeon", "surgery",
        "surpass", "surplus", "surprise", "surrender", "surround",
        "surroundings", "survey", "survive", "survival", "susceptible",
        "suspect", "suspend", "suspicion", "suspicious", "sustain", "swallow",
        "swamp", "swan", "swarm", "sway", "swear", "sweat", "sweep", "sweet",
        "swell", "swift", "swim", "swing", "switch", "sword", "symbol",
        "symbolic", "sympathy", "symptom", "syndrome", "synthesis",
        "synthetic", "system",
        // T
        "table", "tablet", "tackle", "tactic", "tail", "tailor", "take",
        "tale", "talent", "talk", "tall", "tame", "tan", "tank", "tap",
        "tape", "target", "tariff", "task", "taste", "tax", "taxi", "tea",
        "teach", "teacher", "team", "tear", "tease", "technical",
        "technique", "technology", "tedious", "teenager", "telephone",
        "telescope", "television", "tell", "temper", "temperature", "temple",
        "temporal", "temporary", "tempt", "ten", "tenant", "tend", "tendency",
        "tender", "tennis", "tense", "tension", "tent", "tentative", "term",
        "terminal", "terminate", "terms", "terrace", "terrible", "terrific",
        "territory", "terror", "test", "testify", "testimony", "text",
        "textbook", "texture", "than", "thank", "that", "the", "theater",
        "theft", "theme", "then", "theory", "therapy", "there", "thereby",
        "therefore", "these", "thesis", "they", "thick", "thief", "thin",
        "thing", "think", "third", "thirst", "this", "thorn", "thorough",
        "those", "though", "thought", "thoughtful", "thousand", "thread",
        "threat", "threaten", "threshold", "thrift", "thrill", "thrive",
        "throat", "throne", "through", "throughout", "throw", "thrust",
        "thumb", "thus", "tick", "tide", "tidy", "tie", "tight", "tile",
        "tilt", "timber", "time", "timid", "tin", "tiny", "tip", "tire",
        "tired", "tissue", "title", "to", "toast", "tobacco", "today",
        "toe", "together", "toilet", "tolerable", "tolerance", "tolerate",
        "toll", "tomato", "tomorrow", "ton", "tone", "tongue", "tonight",
        "too", "tool", "tooth", "top", "topic", "torch", "torment", "tornado",
        "torrent", "torture", "toss", "total", "touch", "tough", "tour",
        "tourist", "tournament", "toward", "towel", "tower", "town", "toxic",
        "toy", "trace", "track", "trade", "trademark", "tradition",
        "traditional", "traffic", "tragedy", "tragic", "trail", "train",
        "training", "trait", "traitor", "tram", "tramp", "tranquil",
        "transaction", "transcend", "transfer", "transform", "transformation",
        "transient", "transit", "transition", "translate", "translation",
        "transmit", "transparent", "transport", "trap", "trash", "travel",
        "tray", "tread", "treason", "treasure", "treat", "treaty", "tree",
        "tremble", "tremendous", "trench", "trend", "trial", "tribe",
        "trick", "trifle", "trigger", "trim", "trip", "triple", "triumph",
        "trivial", "troop", "trophy", "tropical", "trouble", "trousers",
        "truck", "true", "trumpet", "trunk", "trust", "truth", "try", "tube",
        "tuck", "tuition", "tumble", "tune", "tunnel", "turbulent", "turkey",
        "turn", "turnover", "tutor", "twice", "twin", "twist", "type",
        "typical", "tyrant",
        // U
        "ugly", "ultimate", "ultimately", "umbrella", "unable", "unaware",
        "uncertain", "uncertainty", "uncle", "uncomfortable", "unconscious",
        "uncover", "under", "undergo", "undergraduate", "underground",
        "underline", "undermine", "underneath", "understand", "understanding",
        "undertake", "underwear", "undo", "undoubtedly", "uneasy", "unemployed",
        "unemployment", "unexpected", "unfair", "unfold", "unfortunate",
        "unfortunately", "unhappy", "uniform", "unify", "union", "unique",
        "unit", "unite", "unity", "universal", "universe", "university",
        "unless", "unlike", "unlikely", "until", "unusual", "up", "update",
        "upgrade", "uphold", "upon", "upper", "upright", "upset", "upstairs",
        "upward", "urban", "urge", "urgent", "usage", "use", "used", "useful",
        "useless", "user", "usual", "usually", "utility", "utilize",
        "utmost", "utter", "utterly",
        // V
        "vacant", "vacation", "vaccine", "vacuum", "vague", "vain", "valid",
        "validity", "valley", "valuable", "value", "van", "vanish", "vanity",
        "vapor", "variable", "variation", "variety", "various", "vary",
        "vast", "vegetable", "vehicle", "veil", "vein", "velocity", "velvet",
        "venture", "verb", "verbal", "verdict", "verge", "verify", "versatile",
        "verse", "version", "versus", "vertical", "very", "vessel", "veteran",
        "veto", "via", "vibrate", "vice", "vicinity", "vicious", "victim",
        "victory", "view", "viewpoint", "vigor", "village", "villain",
        "violate", "violence", "violent", "violet", "virtue", "virtually",
        "virtue", "virus", "visible", "vision", "visit", "visitor", "visual",
        "vital", "vivid", "vocabulary", "vocation", "voice", "void", "volume",
        "voluntary", "volunteer", "vote", "voyage", "vulnerable",
        // W
        "wage", "wagon", "waist", "wait", "waiter", "wake", "walk", "wall",
        "wander", "want", "war", "ward", "warehouse", "warm", "warn", "warrant",
        "warrior", "wash", "waste", "watch", "water", "waterfall", "wave",
        "wax", "way", "we", "weak", "weaken", "wealth", "wealthy", "weapon",
        "wear", "weary", "weather", "weave", "wedding", "weed", "week",
        "weekday", "weekend", "weekly", "weep", "weigh", "weight", "weird",
        "welcome", "welfare", "well", "west", "western", "wet", "whale",
        "what", "whatever", "whatsoever", "wheat", "wheel", "when", "whenever",
        "where", "whereas", "wherever", "whether", "which", "while", "whip",
        "whisper", "whistle", "white", "who", "whoever", "whole", "wholly",
        "whom", "whose", "why", "wicked", "wide", "widen", "widespread",
        "widow", "width", "wife", "wild", "wildlife", "will", "willing",
        "win", "wind", "window", "wine", "wing", "wink", "winner", "winter",
        "wipe", "wire", "wisdom", "wise", "wish", "wit", "with", "withdraw",
        "wither", "withhold", "within", "without", "witness", "wolf", "woman",
        "wonder", "wonderful", "wood", "wooden", "wool", "word", "work",
        "worker", "workshop", "world", "worldwide", "worm", "worry", "worse",
        "worship", "worst", "worth", "worthwhile", "worthy", "would", "wound",
        "wrap", "wrath", "wreck", "wrestle", "wretched", "wrinkle", "wrist",
        "write", "writer", "writing", "wrong",
        // X, Y, Z
        "x-ray", "yard", "year", "yearn", "yell", "yellow", "yes", "yesterday",
        "yet", "yield", "young", "youngster", "youth", "zeal", "zebra", "zero",
        "zone", "zoo"
    ]
}
